version: "3.9"
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: client/igamedb
      dockerfile: Dockerfile
    volumes:
      - ./client/igamedb:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./client/igamedb/.env

  nestapp:
    container_name: nestapp
    image: server/nestapp:1.0.0
    build: 
      context: server/igamedb-backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: radmin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  pgdata: {}
  pgadmin-data: {}